version: "3.4"

# Volume to hold elasticsearch data
volumes:
  esdata:

# Network for internal communication among ELK
# components.
networks:
  elk:
    driver: bridge

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    networks:
      - elk
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    expose:
      - "9200"
      - "9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./services/elk/elasticsearch/config:/usr/share/elasticsearch/config/

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    networks:
      - elk
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - xpack.security.enabled=false
    volumes:
      - ./services/elk/kibana/config:/usr/share/kibana/config/

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.1
    networks:
      - elk
    depends_on:
      - elasticsearch
    expose:
      - "5959"
    volumes:
      - ./services/elk/logstash/config:/usr/share/logstash/config/
      - ./services/elk/logstash/pipeline:/usr/share/logstash/pipeline/

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.5.1
    depends_on:
      - kibana
      - elasticsearch
    networks:
      - elk
    volumes:
      - ./services/elk/metricbeat/config:/usr/share/metricbeat/config/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["-e", "-c", "/usr/share/metricbeat/config/metricbeat.yml"]
    user: root
    restart: on-failure
    # often metricbeat won't find Kibana, b/c Kibana is slow to start.
    # Using a restart policy means we'll keep trying. There is probably
    # a better way here, but this work for now.
